<?php

namespace app\form;

use app\component\Constants;
use app\models\ProductCompanyMapping;
use app\models\Products;
use yii\base\Model;

class ProductCompanyForm extends Model
{
    public $company_id;
    public $product;
    public $credentials;
    public $headers;
    public $allowed_api;

    public function setAttributes($values, $safeOnly = true)
    {
        parent::setAttributes($values, false);
    }

    public function rules()
    {
        return [
            [['company_id', 'credentials','allowed_api'], 'required'],
            [["headers"],"safe"],
            [['company_id'], 'integer'],
            [['credentials'], 'validateMultipleData']
        ];
    }

    public function scenarios()
    {
        return [
            'create' => ['company_id', 'credentials','headers','allowed_api'],
            'update' => ['company_id', 'credentials','headers','allowed_api']
        ];
    }


    public function beforeValidate()
    {
        $product_ids = !empty($this->credentials) ? array_keys($this->credentials) : [];
        $this->product = [];
        if (!empty($product_ids)) {
            $this->product = Products::find()->where(["id" => array_keys($this->credentials)])->indexBy('id')->all();
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function validateMultipleData($attribute, $params)
    {
        if (is_array($this->$attribute)) {
            foreach ($this->$attribute as $key => $value) {
                if ($this->product[$key]->authentication_type == Constants::AUTH_TYPE_LOGIN) {
                    if (!isset($value['username']) || !isset($value['password'])) {
                        $this->addError($attribute, "Invalid value for $attribute");
                    }
                } else if ($this->product[$key]->authentication_type == Constants::AUTH_TYPE_TOKEN) {
                    if (!isset($value['token'])) {
                        $this->addError($attribute, "Invalid value for $attribute");
                    }
                }
            }
        }
    }

    public function save()
    {
        if (!$this->hasErrors()) {
            foreach ($this->credentials as $product_id => $credential) {
                $cred = ProductCompanyMapping::findOne(["company_id" => $this->company_id, "product_id" => $product_id]);
                if (!$cred instanceof ProductCompanyMapping) {
                    $cred = new ProductCompanyMapping(["scenario" => ProductCompanyMapping::SCENARIO_CREATE]);
                    $cred->company_id = $this->company_id;
                    $cred->product_id = $product_id;
                    $cred->status = Constants::STATUS_ACTIVE;
                }
                $cred->headers = !empty($this->headers[$product_id]) ? $this->headers[$product_id] : [];
                $cred->allowed_api = !empty($this->allowed_api[$product_id]) ? array_values($this->allowed_api[$product_id]) : [];
                $cred->credentials = $credential;
                if ($cred->validate() && $cred->save()) {
                    continue;
                } else {
                    $this->addErrors($cred->errors);
                }

            }
        }
        return !$this->hasErrors() ? true : false;
    }
}